apiVersion: v1
kind: Secret
metadata:
  name: {{ include "colony.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "colony.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}
  database-url: {{ printf "postgresql://%s:%s@%s-postgresql:%v/%s" (.Values.postgresql.username | urlquery) (.Values.postgresql.password | urlquery) (include "colony.fullname" .) .Values.postgresql.port .Values.postgresql.database | b64enc | quote }}
  secret-key: {{ .Values.backend.env.secretKey | b64enc | quote }}
  admin-password: {{ .Values.backend.env.defaultAdminPassword | b64enc | quote }}
