from enum import Enum


class ErrorCode(str, Enum):
    """Error codes for the households domain."""

    HOUSEHOLD_NOT_FOUND = "HOUSEHOLD_NOT_FOUND"
    HOUSEHOLD_NAME_EXISTS = "HOUSEHOLD_NAME_EXISTS"
    USER_ALREADY_IN_HOUSEHOLD = "USER_ALREADY_IN_HOUSEHOLD"
    USER_NOT_IN_HOUSEHOLD = "USER_NOT_IN_HOUSEHOLD"
    USER_HAS_NO_ACTIVE_HOUSEHOLD = "USER_HAS_NO_ACTIVE_HOUSEHOLD"
