class ErrorCode:
    """Authentication error codes."""
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INACTIVE_USER = "INACTIVE_USER"
    INVALID_TOKEN = "INVALID_TOKEN"  # noqa: S105
    TOKEN_EXPIRED = "TOKEN_EXPIRED"  # noqa: S105
    INCORRECT_PASSWORD = "INCORRECT_PASSWORD"  # noqa: S105
    PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK"  # noqa: S105


# JWT Constants
JWT_TOKEN_PREFIX = "Bearer"  # noqa: S105
JWT_SUBJECT = "access"

# Password validation
MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 128
