class ErrorCode:
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INACTIVE_USER = "INACTIVE_USER"
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INCORRECT_PASSWORD = "INCORRECT_PASSWORD"
    PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK"


# JWT Constants
JWT_TOKEN_PREFIX = "Bearer"
JWT_SUBJECT = "access"

# Password validation
MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 128
